# Generated by Django 4.1.6 on 2023-04-27 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nur',
            options={'ordering': ['id'], 'verbose_name': 'Известные гаджеты', 'verbose_name_plural': 'Известные гаджеты'},
        ),
        migrations.AddField(
            model_name='nur',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
